<?php

namespace UploadBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class FichierRepository extends EntityRepository
{
    const requestBase =
        "SELECT f " .
        "FROM UploadBundle:Fichier f " .
        "WHERE f.lifetime >= :now ".
        "AND f.active = :active ";

    const requestBaseOld =
        "SELECT f " .
        "FROM UploadBundle:Fichier f " .
        "WHERE f.lifetime <= :now ".
        "AND f.active = :active ";


    function getAll($filer=false,$order='DESC')
    {

        $queryString = ($filer=='old'?self::requestBaseOld . "ORDER BY f.lifetime  ".$order : self::requestBase . "ORDER BY f.lifetime ".$order);


        $query = $this->_em->createQuery($queryString);
        $query->setParameter(":now", new \DateTime($filer=='archives'?'0000-00-00':'now'));
        $query->setParameter(":active", ($filer=='archives'?false:true));
  
        return $query->getResult();
    }


    function getFichier($slug)
    {
        $queryString = self::requestBase . " AND f.path='".$slug."' " ;
        $query = $this->_em->createQuery($queryString);
        $query->setParameter(":now", new \DateTime("now"));
        $query->setParameter(":active", true);
 
        return $query->getOneOrNullResult();
    }
}
